### HELP
GET http://localhost:3001/info

### GET ALL
GET http://localhost:3001/api/persons

### GET FOR ID
GET http://localhost:3001/api/persons/4

### DELETE FOR ID
DELETE http://localhost:3001/api/persons/4

### SAVE NEW NOTE
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dairon Casas",
    "number": "3016958000"
}

### UPDATE OLD NOTE
