### HELP
GET http://localhost:3002/help

### GET ALL
GET http://localhost:3002/api/phonebook

### GET FOR ID
GET http://localhost:3002/api/phonebook/67e1960b432d4025df9d9862

### DELETE FOR ID
DELETE http://localhost:3002/api/phonebook/67e0af039a44fb4732778305

### SAVE NEW NOTE
POST http://localhost:3002/api/phonebook
Content-Type: application/json

{
    "name": "Dairon Castro",
    "phone": 3016958000
}

### UPDATE OLD NOTE
PUT http://localhost:3002/api/phonebook/67e1960b432d4025df9d9862
Content-Type: application/json

{
    "name": "Dairon Casas",
    "phone": 3016958000
}
